server:
    port: 11190

logging:
    level:
        ROOT: INFO
        com.profounddistortion: DEBUG
        org.springframework: WARN

spring:
    profiles:
        active: dev
    main:
        banner-mode: "off"
    datasource:
        platform: mysql
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/puzzle?useSSL=false
        username: root
        password: abcd.1234
        validationQuery: SELECT 1
        initialize: true
        continue-on-error: true
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
    jackson:
        serialization:
            fail-on-empty-beans: false

jwt:
    secret:
        key: MySuperSecretKey
    expire:
        millis: 3600000
